name: C/C++ CI

on:
  push:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: Clean
      run: make clean
    - name: Build
      run: make default
    - name: Test
      run: make test